// Code generated by protoc-gen-go. DO NOT EDIT.
// source: polling.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PollRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PollRequest) Reset()         { *m = PollRequest{} }
func (m *PollRequest) String() string { return proto.CompactTextString(m) }
func (*PollRequest) ProtoMessage()    {}
func (*PollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_polling_0e8c8b0c3c9288fa, []int{0}
}
func (m *PollRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollRequest.Unmarshal(m, b)
}
func (m *PollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollRequest.Marshal(b, m, deterministic)
}
func (dst *PollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollRequest.Merge(dst, src)
}
func (m *PollRequest) XXX_Size() int {
	return xxx_messageInfo_PollRequest.Size(m)
}
func (m *PollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PollRequest proto.InternalMessageInfo

func (m *PollRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type PollResponse struct {
	Distance             uint64   `protobuf:"varint,1,opt,name=distance,proto3" json:"distance,omitempty"`
	ClaimableTokens      uint64   `protobuf:"varint,2,opt,name=claimableTokens,proto3" json:"claimableTokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PollResponse) Reset()         { *m = PollResponse{} }
func (m *PollResponse) String() string { return proto.CompactTextString(m) }
func (*PollResponse) ProtoMessage()    {}
func (*PollResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_polling_0e8c8b0c3c9288fa, []int{1}
}
func (m *PollResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollResponse.Unmarshal(m, b)
}
func (m *PollResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollResponse.Marshal(b, m, deterministic)
}
func (dst *PollResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollResponse.Merge(dst, src)
}
func (m *PollResponse) XXX_Size() int {
	return xxx_messageInfo_PollResponse.Size(m)
}
func (m *PollResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PollResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PollResponse proto.InternalMessageInfo

func (m *PollResponse) GetDistance() uint64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *PollResponse) GetClaimableTokens() uint64 {
	if m != nil {
		return m.ClaimableTokens
	}
	return 0
}

type RegisterRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_polling_0e8c8b0c3c9288fa, []int{2}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type RegisterResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_polling_0e8c8b0c3c9288fa, []int{3}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*PollRequest)(nil), "polling.PollRequest")
	proto.RegisterType((*PollResponse)(nil), "polling.PollResponse")
	proto.RegisterType((*RegisterRequest)(nil), "polling.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "polling.RegisterResponse")
}

func init() { proto.RegisterFile("polling.proto", fileDescriptor_polling_0e8c8b0c3c9288fa) }

var fileDescriptor_polling_0e8c8b0c3c9288fa = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xc8, 0xcf, 0xc9,
	0xc9, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xd4, 0xb9,
	0xb8, 0x03, 0xf2, 0x73, 0x72, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x24, 0xb8, 0xd8,
	0x13, 0x53, 0x52, 0x8a, 0x52, 0x8b, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0x60, 0x5c,
	0xa5, 0x10, 0x2e, 0x1e, 0x88, 0xc2, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x29, 0x2e, 0x8e,
	0x94, 0xcc, 0xe2, 0x92, 0xc4, 0xbc, 0xe4, 0x54, 0xb0, 0x52, 0x96, 0x20, 0x38, 0x5f, 0x48, 0x83,
	0x8b, 0x3f, 0x39, 0x27, 0x31, 0x33, 0x37, 0x31, 0x29, 0x27, 0x35, 0x24, 0x3f, 0x3b, 0x35, 0xaf,
	0x58, 0x82, 0x09, 0xac, 0x04, 0x5d, 0x58, 0x49, 0x9b, 0x8b, 0x3f, 0x28, 0x35, 0x3d, 0xb3, 0xb8,
	0x24, 0xb5, 0x88, 0xb0, 0x13, 0x54, 0xb8, 0x04, 0x10, 0x8a, 0xa1, 0xce, 0x10, 0xe0, 0x62, 0x2e,
	0x2d, 0xca, 0x01, 0xab, 0xe4, 0x0c, 0x02, 0x31, 0x8d, 0xda, 0x18, 0xb9, 0xf8, 0x02, 0x20, 0xbe,
	0x0b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x32, 0xe6, 0x62, 0x01, 0x89, 0x08, 0x89, 0xe8,
	0xc1, 0x42, 0x01, 0xc9, 0xcf, 0x52, 0xa2, 0x68, 0xa2, 0x50, 0x93, 0xed, 0xb9, 0x38, 0x60, 0xb6,
	0x09, 0x49, 0xc0, 0x95, 0xa0, 0xb9, 0x56, 0x4a, 0x12, 0x8b, 0x0c, 0xc4, 0x00, 0x27, 0x96, 0x28,
	0xa6, 0x82, 0xa4, 0x24, 0x36, 0x70, 0x80, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xec, 0xc5,
	0x4d, 0x4a, 0x81, 0x01, 0x00, 0x00,
}
